name: CI

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    lint:
        strategy:
            fail-fast: true
            matrix:
                python-version: [3.12]
                os: [ubuntu-latest]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{matrix.python-version}}
            - name: Check file encodings
              run: |
                  sudo apt-get install -y python3-chardet
                  for file in $(find . -type f \( -name "setup.py" -o -name "requirements.txt" \)); do
                      echo "Checking encoding for $file"
                      chardet $file
                  done
            - name: Install Project
              run: pip install '.[test]'
            - name: Look for style errors
              run: ruff check .\lazydm\ .\tests\
